### ISSUE TITLE
When is it necessary to define a new Metadata?

### ISSUE THREAD

**Issue by RF-Tar-Railt** [GraiaProject/Avilla#101]
敲定在什么情况下需要创建平台特定的metadata

假设 A平台可以获取一个数据类 Foo, 其 id 为 `land.xxx.foo`
那么：

1. 若 Foo 的属性有 name, count 之类的，是否规定直接通过 `pull(land.xxx.foo, Summary / Count)` 获取数据，而非创建元数据 Foo 并 `pull(land.xxx.foo, Foo)`

2. 若创建 Foo , 那么是否仍然支持  `pull(land.xxx.foo, Summary / Count)` 获取数据，或需要 `pull(land.xxx.foo, Foo >> Count)`

3.  若创建 Foo, 那么是否需要尽可能的将 Foo 数据所具有的字段塞入 Foo 中
4. 若不创建 Foo, 那么如何获取 Foo 上一个现有 metadata 无法描述的字段

**Comment by GreyElaina** [comment]
会需要考虑该特性是否为平台特有特性。

如果是，则创建 `Foo`.
如果确认为否，则补全 `standards.core`, 使之能够描述。
