### ISSUE TITLE
Question: How to interrupt a running `on_message_received`?

### ISSUE THREAD

**Issue by markyfsun** [GraiaProject/Avilla#165]
Thank you for this elegant work!

I am using a Large Language Model to drive a QQ bot. Here is my use case:

1. When user send a message to the bot, Avilla calls `on_message_received`
2. `on_message_received` sends multiple messages to the user, which takes tens of seconds:
```
for response in llm_stream(...):
    await ctx.scene.send_message(...)
    # <- I want to interrupt here
```
3. User sends another message to the bot before previous `on_message_received` completes
4. Availla cancels previous unfinished `on_message_received` and launches a new `on_message_received`

I have looked into the documents and found `interrupt` in [broadcast](https://graia.readthedocs.io/ariadne/extra/broadcast/interrupt/). However, it does not provide a "interrupt in the middle" function.

I am planning to use `celery` to handle `on_message_received` as background task, but I hope there is a more Avilla-native way.

**Comment by GreyElaina** [comment]
~~use Broadcast Control's Waiter, but chinese docs provided only.~~

Waiter & `asyncio.wait_for`.

```python
try:
    await asyncio.wait_for(waiter.wait(), timeout=5)
expect TimeoutError:
    ...  # do cancelled
else:
    ...  # do else

```

**Comment by RF-Tar-Railt** [comment]
Here is my example to use Interrupt in loop:
https://github.com/RF-Tar-Railt/RaianBot/blob/38744a0852087b3aa09ed9cb080cb43b057469b9/plugins/guess_operator/main.py#L105-L145

`FunctionWaiter` : https://github.com/RF-Tar-Railt/RaianBot/blob/38744a0852087b3aa09ed9cb080cb43b057469b9/app/interrupt.py#L3-L87

**Comment by markyfsun** [comment]
感谢大佬们的及时回复！

我查阅了`Waiter`相关文档，还是有一个问题。

我理解`Waiter`的工作原理是：
1. 用户发送消息，触发`on_message_received`
2. 做一些事情，比如发回一些消息
3. 启动`Waiter`绑定`func`函数并监听`MessageReceived`事件持续一段时间，假设20秒
4. 如果20秒内没有新消息收到，那么`Waiter`抛出`TimeoutError`
5. 如果20秒内收到了新消息，那么调用`func`函数，将该函数的返回值返回

我现在的情况是：我需要在第二步“做一些事情”的同时，监听`MessageReceived`事件。
而目前`Waiter`似乎是阻塞式的监听？

**Comment by markyfsun** [comment]
`asyncio.create_task`看起来更适合我的场景，我准备参考[后台任务](https://graia.readthedocs.io/ariadne/feature/background/)实现。

非常感谢！♪(･ω･)ﾉ
