### ISSUE TITLE
More applicable message serialization/deserialization method

### ISSUE THREAD

**Issue by RF-Tar-Railt** [GraiaProject/Avilla#95]
consider some client supply the message as a str

**Comment by GreyElaina** [comment]
我认为你应该先将 str 形式的 message 解析为 list[dict[Any, Any], Ryanvk 现有的模型, 经过思考后, 我认为不宜增加更多的 "通用化设计", 这会显著增加负担.

**Comment by GreyElaina** [comment]
我会考虑将 `MessageDeserialize` 改名为 `ElementDeserialize`, 并加入 `Staff.deserialize_element` 方法.
